export interface FootballerDetail{
    id : number,
    clubId : number,
    leagueId : number,
    countryId : number,
    footballerImagePath : string,
    clubImagePath : string,
    leagueImagePath : string,
    footballerCountryImagePath : string,
    leagueCountryImagePath : string,
    positionName : string,
    name : string,
    dateOfBirth : Date,
    age : number,
    height : number,
    footballerValue : number,
    playerNumber : number,
    footName : string
}